name: Backup Firestore

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if needed
  # Add any additional triggers such as pull_request if required

env:
  PROJECT_ID: tzivoshashemmilwaukee
  BUCKET: gs://achosbackup
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Display gcloud version
        run: gcloud --version

      - name: Set project for gcloud
        run: gcloud config set project $PROJECT_ID

      - name: Run Firestore export
        run: gcloud firestore export $BUCKET