name: Backup Firestore

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: tzivoshashemmilwaukee
  BUCKET: gs://backupachostest1

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json

      - run: gcloud info

      - run: gcloud config set project $PROJECT_ID

      - run: gcloud firestore export $BUCKET




